
services:

  apache:
    image: httpd:latest
    container_name: apache
    restart: always
    volumes:
      - ../:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"

  php8:
    build: .
    container_name: carnetAdresse
    restart: always
    volumes:
      - ../:/var/www/html/
    ports:
      - "80:80"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
    links:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
